# Default htscodecs.mk generated by Makefile
include $(HTSPREFIX)htscodecs_bundled.mk
# Compiler probe results, generated by ./hts_probe_cc.sh
HTS_HAVE_CPUID = 1
HTS_CFLAGS_SSE4 = -msse4.1 -mpopcnt -mssse3
HTS_BUILD_SSE4 = 1
HTS_CFLAGS_AVX2 = -mavx2 -mpopcnt
HTS_BUILD_AVX2 = 1
HTS_CFLAGS_AVX512 = -mavx512f -mpopcnt
HTS_BUILD_AVX512 = 1
HTS_HAVE_SSSE3_BUILTINS = 1
